cp -f thirdparty/capicon/svg/059.svg resources/add.svg
cp -f thirdparty/capicon/svg/262.svg resources/select.svg
cp -f thirdparty/capicon/svg/078.svg resources/picture.svg
cp -f thirdparty/capicon/svg/226.svg resources/save.svg
cp -f thirdparty/capicon/svg/341.svg resources/info.svg
cp -f thirdparty/capicon/svg/279.svg resources/up.svg
cp -f thirdparty/capicon/svg/278.svg resources/down.svg
cp -f thirdparty/capicon/svg/274.svg resources/clip.svg
cp -f thirdparty/capicon/svg/254.svg resources/rangeselect.svg
cp -f thirdparty/capicon/svg/057.svg resources/delete.svg
cp -f thirdparty/capicon/svg/047.svg resources/new.svg
cp -f thirdparty/capicon/svg/039.svg resources/palette.svg
cp -f thirdparty/capicon/svg/030.svg resources/trashbin.svg
