#ifndef DUST3D_APPLICATION_VERSION_H_
#define DUST3D_APPLICATION_VERSION_H_

#include <QString>

#define APP_COMPANY                 PROJECT_DEFINED_APP_COMPANY
#define APP_NAME                    PROJECT_DEFINED_APP_NAME
#define APP_VER                     PROJECT_DEFINED_APP_VER
#define APP_HUMAN_VER               PROJECT_DEFINED_APP_HUMAN_VER
#define APP_HOMEPAGE_URL            PROJECT_DEFINED_APP_HOMEPAGE_URL
#define APP_REPOSITORY_URL          PROJECT_DEFINED_APP_REPOSITORY_URL
#define APP_ISSUES_URL              PROJECT_DEFINED_APP_ISSUES_URL
#define APP_REFERENCE_GUIDE_URL     PROJECT_DEFINED_APP_REFERENCE_GUIDE_URL
#define APP_UPDATES_CHECKER_URL     PROJECT_DEFINED_APP_UPDATES_CHECKER_URL
#define APP_PLATFORM                PROJECT_DEFINED_APP_PLATFORM

inline QString applicationTitle(const QString &text)
{
    return text + QObject::tr(" - ") + APP_NAME;
}

#endif
