/*
 *  Copyright (c) 2016-2026 Jeremy HU <jeremy-at-dust3d dot org>. All rights reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:

 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.

 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

#ifndef DUST3D_MESH_WRAP_MESH_BUILDER_H_
#define DUST3D_MESH_WRAP_MESH_BUILDER_H_

#include <array>
#include <cstdint>
#include <dust3d/base/uuid.h>
#include <dust3d/base/vector2.h>
#include <dust3d/base/vector3.h>
#include <list>
#include <string>
#include <utility>
#include <vector>

namespace dust3d {

// WrapMeshBuilder: the wrap modifier of a group component.
//
// The meshes generated by the children of a group (tubes, stitched shells, imported
// models, nested groups) are turned into signed distance fields and blended into one
// volume. One new surface is then extracted around that volume:
//
//   Skin   a tight, watertight surface that follows the children and blends the
//          creases between them (a bust into the chest, a shoulder into the torso), so
//          the result has no inner faces and no boolean seams.
//   Cloth  a loose surface over the children: bridges the gaps between them (no
//          cleavage), sits an offset above them, hangs down under overhangs (drape),
//          can be opened (an Inversion child cuts an opening of its shape: a neckline,
//          an armhole; or flat cuts at the top and bottom) and given a real thickness.
//
// The surface is all quads with edge flow: a fine surface is extracted from the field
// (surface nets, projected onto the iso-surface and relaxed), then remeshed by the
// AutoRemesher core (third_party/autoremesher): a curvature aligned cross field, a
// mixed-integer quad parameterization and quad extraction. Edge loops run around the
// limbs, the neck and the torso, and along the creases where openings are cut. The
// face count is set directly, so it can be budgeted. (If the remesher fails, the grid
// surface at the wanted face count is used instead.)
//
// Every output vertex also gets skin weights: the nodes of the children it covers,
// found by transferring weights from the children's surfaces (the nearest source
// vertices, each of which is known to come from one node) and smoothing them over the
// new surface. The rig generator turns the node weights into bone weights, so the
// wrap is bound to the same bones as the children, the way the editor already binds
// every part: bones are assigned to the children's edges, nothing else is needed.
class WrapMeshBuilder {
public:
    enum class Mode {
        Skin = 0,
        Cloth
    };

    struct Parameters {
        Mode mode = Mode::Skin;
        // Distance between the children and the wrap surface.
        double offset = 0.0;
        // Blend radius between children: creases narrower than this are filled.
        double smoothness = 0.02;
        // Cloth only, 0..1: how straight the surface falls from an overhang (a bust,
        // a belly, the hips) instead of following the body back in under it.
        double drape = 0.0;
        // Cloth only: the furthest the cloth falls below what holds it up (0 = no limit).
        double drapeLength = 0.0;
        // Wanted number of quads on the surface (before thickness is added).
        size_t targetFaces = 1600;
        // Cloth only: open the surface at these fractions of the children's height,
        // measured down from the top and up from the bottom (0 = closed).
        double openTop = 0.0;
        double openBottom = 0.0;
        // Cloth only: shell thickness of an open surface (0 = single sided).
        double thickness = 0.0;
        // AutoRemesher's "Smooth Normal" (degrees, 0..180; 0 = off): the remesher projects
        // onto a smooth (PN triangle) surface through the fine surface's vertex normals,
        // averaged over faces within this angle, instead of onto its flat facets. It is the
        // group's "Normal Smooth" cutoff.
        double smoothNormalDegrees = 0.0;
        // Relaxation passes over the fine surface extracted from the field (before it is
        // remeshed into quads).
        int relaxIterations = 6;
        // Smoothing passes over the transferred skin weights (0 = automatic).
        int weightSmoothIterations = 0;
        // Weight transfer blend distance in world units (0 = 0.03): the same for a body and
        // the garments over it, so they bend alike at the joints.
        double weightRadius = 0.0;
        // The group's name, for log messages.
        std::string label;
    };

    struct NodeWeight {
        Uuid nodeId;
        float weight = 0.0f;
    };

    // Results of earlier builds, keyed by their inputs (owned by the caller, e.g. the mesh
    // generator's cache context, so it lives across generations of one document):
    //   the surface (field, quad remesh, openings, thickness, UVs) is reused when the sources
    //   and the shape settings are the same, whatever else about the group changed (its
    //   colour, a child's colour, its weight settings, the body a garment is bound to);
    //   the skin weights are reused when the bind samples, nodes and weight settings are too.
    struct CachedResult {
        uint64_t surfaceKey = 0;
        uint64_t weightKey = 0;
        bool hasWeights = false;
        std::vector<Vector3> vertices;
        std::vector<std::vector<size_t>> faces;
        std::vector<size_t> vertexSourceVertex;
        double cellSize = 0.0;
        bool remeshed = false;
        std::vector<Vector3> resultVertices;
        std::vector<std::vector<size_t>> resultTriangles;
        std::vector<std::vector<size_t>> resultTriangleAndQuads;
        std::vector<std::pair<size_t, size_t>> resultQuadDiagonals;
        std::vector<std::array<Vector2, 3>> resultTriangleUvs;
        std::vector<std::vector<NodeWeight>> resultVertexNodeWeights;
    };
    struct Cache {
        // most recently used first; a few entries cover undo/redo and toggling a setting back
        std::list<CachedResult> entries;
        size_t capacity = 12;
    };
    void setCache(Cache* cache) { m_cache = cache; }
    // How the last build() got its result: 0 built, 1 surface reused, 2 surface and weights reused.
    int cacheLevel() const { return m_cacheLevel; }

    void setParameters(const Parameters& parameters);
    // A closed mesh to wrap. Faces may be triangles or polygons.
    void addSource(const std::vector<Vector3>& vertices,
        const std::vector<std::vector<size_t>>& faces,
        bool subtract = false);
    // A point on a source surface that is known to come from a node (for skin weights).
    void addBindSample(const Vector3& position, const Uuid& nodeId);
    // Drop the samples added so far (the weights then come only from samples added after).
    void clearBindSamples() { m_bindSamples.clear(); }
    // The nodes the samples refer to, as spheres, and how they connect. With these, a
    // vertex only blends the nodes near the one it is closest to in this graph (two hops),
    // so weights never jump across a gap: the left foot does not pull on the right foot,
    // the ribs do not pull on the hanging arm.
    struct BindNode {
        Uuid id;
        Vector3 position;
        double radius = 0.0;
        std::string group; // nodes of one part (its edges link them)
        std::string twinGroup; // the part it mirrors, or its own part: twins never touch
    };
    void addBindNode(const BindNode& node) { m_bindNodes.push_back(node); }
    void addBindLink(const Uuid& a, const Uuid& b) { m_bindLinks.push_back({ a, b }); }
    std::vector<Uuid> bindNodeIds() const;
    size_t bindSampleCount() const { return m_bindSamples.size(); }

    bool build();

    const std::vector<Vector3>& resultVertices() const { return m_resultVertices; }
    const std::vector<std::vector<size_t>>& resultTriangles() const { return m_resultTriangles; }
    // Triangles merged back into the quads they came from (for edge flow / export).
    const std::vector<std::vector<size_t>>& resultTriangleAndQuads() const { return m_resultTriangleAndQuads; }
    // The diagonal of every quad that was split into two triangles.
    const std::vector<std::pair<size_t, size_t>>& resultQuadDiagonals() const { return m_resultQuadDiagonals; }
    // Up to MaxNodeInfluences node weights per vertex, normalized.
    const std::vector<std::vector<NodeWeight>>& resultVertexNodeWeights() const { return m_resultVertexNodeWeights; }
    // UVs of every result triangle, in [0, 1].
    const std::vector<std::array<Vector2, 3>>& resultTriangleUvs() const { return m_resultTriangleUvs; }
    // Grid cell size that was used.
    double cellSize() const { return m_cellSize; }
    const std::string& errorMessage() const { return m_errorMessage; }

    static const size_t MaxNodeInfluences = 6;

private:
    struct Source {
        std::vector<Vector3> vertices;
        std::vector<std::array<size_t, 3>> triangles;
        bool subtract = false;
    };

    struct Grid {
        int nx = 0;
        int ny = 0;
        int nz = 0;
        Vector3 origin;
        double h = 1.0;
        std::vector<float> values;
        size_t index(int i, int j, int k) const { return ((size_t)k * ny + j) * nx + i; }
        Vector3 position(int i, int j, int k) const { return origin + Vector3(i * h, j * h, k * h); }
    };

    uint64_t surfaceKey() const;
    uint64_t weightKey() const;
    bool buildSurface();
    bool buildAtCellSize(double cellSize);
    void computeField(double cellSize);
    void addSourceToField(const Source& source, double band);
    void disambiguate();
    void smoothField(int passes, float limit);
    void applyDrape();
    void applyOpenings();
    double sampleField(const Vector3& position) const;
    double sampleCarve(const Vector3& position) const;
    double sampleGrid(const std::vector<float>& values, const Vector3& position) const;
    Vector3 sampleGradient(const Vector3& position) const;
    Vector3 projectToSurface(const Vector3& position) const;
    Vector3 projectToCarve(const Vector3& position) const;
    Vector3 projectToGrid(const std::vector<float>& values, const Vector3& position) const;
    void extractSurface();
    void openSurface();
    void clipOpenings();
    void relaxSurface(bool interior);
    void cutAlongCreases();
    double openingSide(const Vector3& position) const;
    bool hasOpenings() const;
    Vector3 projectToCrease(const Vector3& position) const;
    bool remeshQuads(size_t targetFaces);
    void addThickness();
    void triangulate();
    void transferWeights();
    void generateUvs();
    void dumpForDebugging() const;

    Parameters m_parameters;
    std::vector<Source> m_sources;
    std::vector<std::pair<Vector3, Uuid>> m_bindSamples;
    std::vector<BindNode> m_bindNodes;
    std::vector<std::pair<Uuid, Uuid>> m_bindLinks;
    Vector3 m_sourceMin;
    Vector3 m_sourceMax;
    double m_cellSize = 0.0;
    double m_openTopY = 0.0;
    double m_openBottomY = 0.0;
    Grid m_grid;
    // Signed distance to the carving (subtracted) sources, where there are any.
    std::vector<float> m_carve;
    // Cloth: the field before carving and flat cuts (the creases of openings lie on it).
    std::vector<float> m_baseField;
    bool m_remeshed = false;

    // Surface under construction: polygons (quads, a few triangles after opening).
    std::vector<Vector3> m_vertices;
    std::vector<std::vector<size_t>> m_faces;
    std::vector<bool> m_vertexOnOpening;
    // Inner shell (thickness): for each vertex, its outer twin (or itself).
    std::vector<size_t> m_vertexSourceVertex;

    std::vector<Vector3> m_resultVertices;
    std::vector<std::vector<size_t>> m_resultTriangles;
    std::vector<std::vector<size_t>> m_resultTriangleAndQuads;
    std::vector<std::pair<size_t, size_t>> m_resultQuadDiagonals;
    std::vector<std::vector<NodeWeight>> m_resultVertexNodeWeights;
    std::vector<std::array<Vector2, 3>> m_resultTriangleUvs;
    std::string m_errorMessage;
    Cache* m_cache = nullptr;
    int m_cacheLevel = 0;
};

}

#endif
