#ifndef GLW_STYLE_H
#define GLW_STYLE_H

#define GLW_SYSTEM_FONT_NAME    "Helvetica"
#define GLW_SYSTEM_FONT_WEIGHT  5
#define GLW_SYSTEM_FONT_SIZE    21

#define GLW_SMALL_ROUNDED_CORNER_SLICES 5

#define GLW_BORDER_COLOR_1 0xa2a2a2
#define GLW_BORDER_COLOR_2 0x616161

#define GLW_FILL_GRADIENT_COLOR_1 0xffffff
#define GLW_FILL_GRADIENT_COLOR_2 0xc6c4c5

#define GLW_FILL_GRADIENT_COLOR_1_H 0x3795fa
#define GLW_FILL_GRADIENT_COLOR_2_H 0x333333

#define GLW_BUTTON_CORNER_RADIUS 5

#define GLW_CHECK_COLOR 0x000000

#define GLW_TAB_FILL_GRADIENT_COLOR_1 0xffffff
#define GLW_TAB_FILL_GRADIENT_COLOR_2 0xc6c4c5

#define GLW_TAB_FILL_GRADIENT_COLOR_1_H 0x3795fa
#define GLW_TAB_FILL_GRADIENT_COLOR_2_H 0x333333

#define GLW_PANEL_FILL_COLOR 0xe2e2e2

#define GLW_HOR_AUTO_MARGIN 0.4
#define GLW_VER_AUTO_MARGIN 0.15

#define GLW_BACKGROUND_COLOR 0xfcfcfc
#define GLW_TOOLBAR_BACKGROUND_COLOR 0xf5f5f5

#endif
