#ifndef GLW_STYLE_H
#define GLW_STYLE_H

#define GLW_SYSTEM_FONT_NAME    "PT Sans Narrow" //"Monaco" //"Helvetica"
#define GLW_SYSTEM_FONT_WEIGHT  10
#define GLW_SYSTEM_FONT_SIZE    20
#define GLW_SYSTEM_FONT_COLOR   0xb9b9b9

#define GLW_SMALL_ROUNDED_CORNER_SLICES 5

#define GLW_BORDER_COLOR_1 0x000000
#define GLW_BORDER_COLOR_2 0x000000

#define GLW_FILL_GRADIENT_COLOR_1 0x424242
#define GLW_FILL_GRADIENT_COLOR_2 0x242424

#define GLW_FILL_GRADIENT_COLOR_1_H 0x3795fa
#define GLW_FILL_GRADIENT_COLOR_2_H 0x242424

#define GLW_BUTTON_CORNER_RADIUS 5

#define GLW_CHECK_COLOR 0x000000

#define GLW_TAB_FILL_GRADIENT_COLOR_1 GLW_FILL_GRADIENT_COLOR_1
#define GLW_TAB_FILL_GRADIENT_COLOR_2 GLW_FILL_GRADIENT_COLOR_2

#define GLW_TAB_FILL_GRADIENT_COLOR_1_H 0x3795fa
#define GLW_TAB_FILL_GRADIENT_COLOR_2_H 0x333333

#define GLW_PANEL_FILL_COLOR 0xe2e2e2

#define GLW_HOR_AUTO_MARGIN 0.4
#define GLW_VER_AUTO_MARGIN 0.15

#define GLW_BACKGROUND_COLOR 0x373737
#define GLW_TOOLBAR_BACKGROUND_COLOR GLW_TAB_FILL_GRADIENT_COLOR_2

#define GLW_MIN_TAB_WIDTH 120

#endif
