#include <QObject>
#include "skeletonbonemark.h"

IMPL_SkeletonSideToDispName

IMPL_SkeletonBoneMarkToColor
IMPL_SkeletonBoneMarkToString
IMPL_SkeletonBoneMarkFromString
IMPL_SkeletonBoneMarkToDispName
